apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: admin-server
    spec:
      containers:
        - image: astoklas177/spring-petclinic-admin-server:latest
          command:
            - /entrypoint.sh
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          livenessProbe:
            exec:
              command:
                - curl
                - -I
                - http://localhost:9090
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 15
          name: admin-server
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
