apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visits-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: visits-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: k8s,mysql
          command:
            - /entrypoint.sh
          image: astoklas177/spring-petclinic-visits-service:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -I
                - http://localhost:8082
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 15
          name: visits-service
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
