apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-nomon.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-nomon.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: astoklas177/spring-petclinic-api-gateway:2025.4.9
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
