apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        image: ${DOCKER_USERNAME}/spring-petclinic-customers-service:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic-dev
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customers-service