apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-nomon.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: genai-service
  name: genai-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    io.kompose.service: genai-service
