apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-nomon.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visits-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-nomon.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: visits-service
    spec:
      containers:
        - image: astoklas177/spring-petclinic-visits-service:2025.4.9
          name: visits-service
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
