zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: k8s
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: api-gateway
    # fixing the hostname to the name of the service in k8s, no real need for service discovery as it's built in
    preferIpAddress: false
    nonSecurePort: 8088
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}