services:
  config-server:
    image: astoklas177/spring-petclinic-config-server:latest
    container_name: config-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
     - 8888:8888
    environment:   
      - JAVA_OPTIONS="$JAVA_OPTIONS -Dspring.profiles.active=native -DGIT_REPO=/projects/spring-petclinic-microservices-config"
      - SPRING_PROFILES_ACTIVE=native
      - GIT_REPO=/projects/spring-petclinic-microservices-config
    volumes:
      - type: bind
        source: ../config/spring-petclinic-microservices-config/
        target: /projects/spring-petclinic-microservices-config/

  discovery-server:
    image: astoklas177/spring-petclinic-discovery-server:latest
    container_name: discovery-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    ports:
     - 8761:8761
    environment:   
      - SPRING_PROFILES_ACTIVE=docker

  customers-service: 
    image: astoklas177/spring-petclinic-customers-service:latest
    container_name: customers-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
    - 8081:8081
    environment:   
      - SPRING_PROFILES_ACTIVE=docker,mysql

  visits-service:
    image: astoklas177/spring-petclinic-visits-service:latest
    container_name: visits-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 8082:8082
    environment:   
      - SPRING_PROFILES_ACTIVE=hybrid,mysql
      - CONFIG_SERVER_URL=http://config-server:8888

  vets-service:
    image: astoklas177/spring-petclinic-vets-service:latest
    container_name: vets-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 8083:8083
    environment:   
      - SPRING_PROFILES_ACTIVE=docker,mysql


  genai-service:
    image: astoklas177/spring-petclinic-genai-service:latest
    container_name: genai-service
    environment:
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 8084:8084


  api-gateway:
    image: astoklas177/spring-petclinic-api-gateway:latest
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 8080:8080
  admin-server:
    image: astoklas177/spring-petclinic-admin-server:latest
    container_name: admin-server
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 9090:9090

  petclinic-db:
    image: biarms/mysql:5.7
    container_name: petclinic-db
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
     - 3306:3306
    volumes:
      - type: bind
        source: ../config/db/
        target: /docker-entrypoint-initdb.d/